version: 2
jobs:
  build:
    working_directory: ~/pfm-api/spring-javaj2eefsd-workshop
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    
    steps:
      - checkout:
          path: ~/pfm-api
      - restore_cache:
          key: pfm-api-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: pfm-api-{{ checksum "pom.xml" }}
      - run: mvn clean install
  